.PHONY: clean All

All:
	@echo "----------Building project:[ faas - Debug ]----------"
	@cd "faas" && "$(MAKE)" -f  "faas.mk"
clean:
	@echo "----------Cleaning project:[ faas - Debug ]----------"
	@cd "faas" && "$(MAKE)" -f  "faas.mk" clean
