.PHONY: clean All

All:
	@echo "----------Building project:[ FAAS_pqNTRU - Debug ]----------"
	@cd "FAAS_pqNTRU" && "$(MAKE)" -f  "FAAS_pqNTRU.mk"
clean:
	@echo "----------Cleaning project:[ FAAS_pqNTRU - Debug ]----------"
	@cd "FAAS_pqNTRU" && "$(MAKE)" -f  "FAAS_pqNTRU.mk" clean
